### PR TITLE
Feature/add skill

### PR DESCRIPTION
**Pull request by Ginohmk**
## Add functionalities to add skill 

- User can click on the `Add skill` button on the home page, which navigates to the `Add skill form`, where skill data is collected and saved on the server side.
- Form validation is also implemented.
-  Skill logo images data structure is mapped with the name of the skill logo, on the client side, where the name is sent to the backend and when a request is made for the skill, the logo name can be used to map the skill data structure on the client side to display the appropriate image logo.

##### Image below
image

### CODE REVIEW

**Comment by Ginohmk** [comment]
@wrussell1999   #9

**Comment by wrussell1999** [comment]
Looking good @Ginohmk! Can you review my suggestions above and then we can get this merged in!

**Comment by Ginohmk** [comment]
@wrussell1999  Please I can't seem to see your suggestions, please where can I find them, so I implement them. ?

**Comment by wrussell1999** [comment]
> @wrussell1999 Please I can't seem to see your suggestions, please where can I find them, so I implement them. ?

@Ginohmk key things are:
- write some tests to show this works
- Separate all the CSS in the JSX code into its own CSS file for easier readability

**Comment by Ginohmk** [comment]
@wrussell1999  

Thanks for your suggestions, I have done the following 
- Separate the styles from the JSX
- Add test for the Home screen and Add skill page

**Review by wrussell1999 — APPROVED** [review]
LGTM

**Pull request merged**
