### PR TITLE
Add experience

### LINKED ISSUE #11: Page for adding a new Experience
Add a page that allows users to add a new Experience which includes the following fields:

- title
- company
- start_date
- end_date
- description
- logo

Collaborate with the fellows contributing to the Python project to understand how logos will be managed. For now, assume this is a string (URL to the image). 

When this information is submitted, a POST request should be made to `/resume/experience` on the server in the following format:

```json
{
    "title": "Software Developer",
    "company": "A Cooler Company",
    "start_date": "October 2022",    
    "end_date": "Present",
    "description": "Writing JavaScript Code",
    "logo": "example-logo.png",
}
```

The server will return a JSON with the position in the list in the following format:
```json
{
"id": 1
}
```

### PR DESCRIPTION
**Pull request by kristinlam**
Closes #11 

## Description

- Created page at /add-experience with form for submitting experiences, which can be accessed by clicking "Add Experience" on homepage.
- Currently have a placeholder input field for the logo, which accepts any string. This will need to be updated when the drag and drop feature is completed. #2 
- Does not currently display the submitted experiences.
- Updated styles to match Mike's in PR #15
- Wrote tests

addexp

### CODE REVIEW

**Comment by kristinlam** [comment]
@wrussell1999 Hi, this is good to go after #15 is merged in! About the force-pushing 3 times — I kept reverting my commits back to "Finetune styles" because I was trying to figure out why, whenever I merged in my updated main branch into this feature branch in my forked repo, it was also automatically committing "Merge remote-tracking branch 'upstream/main' at the same time as "Merge branch 'main' into add-experience". I'm still a little confused by this double merge message.

I left off form validation because I see that it's an issue in the Python repo: https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/13

**Review by wrussell1999 — CHANGES_REQUESTED** [review]
Please use Jest to write a test to show this works successfully

**Comment by wrussell1999** [comment]
> @wrussell1999 Hi, this is good to go after #15 is merged in! About the force-pushing 3 times — I kept reverting my commits back to "Finetune styles" because I was trying to figure out why, whenever I merged in my updated main branch into this feature branch in my forked repo, it was also automatically committing "Merge remote-tracking branch 'upstream/main' at the same time as "Merge branch 'main' into add-experience". I'm still a little confused by this double merge message.
> 
> I left off form validation because I see that it's an issue in the Python repo: [MLH-Fellowship/orientation-project-python-23.SUM.A#13](https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/issues/13)

Looking really good! I’m going to get @Henoven to give you a hand with the git questions here!

**Comment by Henoven** [comment]
> whenever I merged in my updated main branch into this feature branch in my forked repo, it was also automatically committing "Merge remote-tracking branch 'upstream/main' at the same time as "Merge branch 'main' into add-experience". I'm still a little confused by this double merge message

Hey @kristinlam if I understand you are asking why Git giving you this double merge message?

If so, after doing some research I found out the following answer of this behaviour

When merging the main branch from the original repository into your feature branch in your forked repository, Git creates a merge commit with a double merge message. The message indicates the source of the changes (remote-tracking branch) and the target branch (your feature branch), providing clarity on the merge operation.

Let me know if this answers your question : )

**Comment by kristinlam** [comment]
@Henoven thank you so much for the explanation! That clarifies the types of merges for me. 😄 I did first merge the upstream/main into my forked repo's main, then merge my main branch into my feature branch, so that might explain it!

@wrussell1999 I created another test for showing that the form takes inputs and submits POST requests correctly. I was wondering, should I create a mock server to make sure the response being returned is also in the correct format or prioritize completing another issue? I'm new to Jest so will need a little more time to figure out how to test network responses.

**Comment by wrussell1999** [comment]
> @wrussell1999 I created another test for showing that the form takes inputs and submits POST requests correctly. I was wondering, should I create a mock server to make sure the response being returned is also in the correct format or prioritize completing another issue? I'm new to Jest so will need a little more time to figure out how to test network responses.

@kristinlam great stuff! As we're at the end of the week, don't worry about these extra tests but I would encourage you to keep reading about Jest!

**Review by wrussell1999 — APPROVED** [review]

**Pull request merged**
